# Generated by Django 4.0.5 on 2022-06-15 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airfreight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('air_consol', models.CharField(max_length=100)),
                ('air_pic', models.CharField(max_length=100)),
                ('air_chk_date', models.CharField(max_length=100)),
                ('air_origin', models.CharField(max_length=100)),
                ('air_dest', models.CharField(max_length=100)),
                ('air_carrier', models.CharField(max_length=100)),
                ('air_min', models.CharField(max_length=100)),
                ('air_normal', models.CharField(max_length=100)),
                ('air_45kg', models.CharField(max_length=100)),
                ('air_100kg', models.CharField(max_length=100)),
                ('air_300kg', models.CharField(max_length=100)),
                ('air_500kg', models.CharField(max_length=100)),
                ('air_1000kg', models.CharField(max_length=100)),
                ('air_fsc', models.CharField(max_length=100)),
                ('air_iss', models.CharField(max_length=100)),
                ('air_tspoint', models.CharField(max_length=100)),
                ('air_skdl', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chk_date', models.CharField(max_length=100)),
                ('pic_code', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=100)),
                ('dest', models.CharField(max_length=100)),
                ('carrier', models.CharField(max_length=100)),
                ('twenty', models.CharField(max_length=100)),
                ('fourty', models.CharField(max_length=100)),
                ('freq', models.CharField(max_length=100)),
                ('ttime', models.CharField(max_length=100)),
                ('effective', models.CharField(max_length=100)),
                ('scno', models.CharField(max_length=100)),
                ('remark', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
            ],
        ),
    ]
