# Generated by Django 4.0.5 on 2022-07-08 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('employee_register', '0003_lcl'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': [('can_view_goldpage', 'Can View Goldpage')]},
        ),
        migrations.AddField(
            model_name='lcl',
            name='username',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='작성자'),
            preserve_default=False,
        ),
    ]
