# Generated by Django 4.0.5 on 2022-07-18 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0008_remove_airfreight_air_pic_remove_employee_pic_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airfreight',
            name='air_effective',
            field=models.CharField(default=123, max_length=10),
            preserve_default=False,
        ),
    ]
